dist: trusty
sudo: false

language: go

go:
  - "1.10"

before_install:
  - go get github.com/onsi/ginkgo/ginkgo

install:
  # Prevent default install task that does a `go get -t ./...`
  - true

script:
  - make unit
